### ISSUE TITLE
Error: Fts was not replaced on

### ISSUE THREAD

**Issue by shyamal890** [fissoft/Fissoft.EntityFramework.Fts#14] opened 2017-09-22 11:32 UTC
```
FTS was not replaced on: SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [dbo].[Task_tb] AS [Extent1]
        WHERE ([Extent1].[CompanyId] = @p__linq__0) AND (0 = [Extent1].[isArchived]) AND ((([Extent1].[CompanyId] = @p__linq__1) AND (CASE WHEN ([Extent1].[Taskname] IS NULL) THEN N'' ELSE [Extent1].[Taskname] END + CASE WHEN ([Extent1].[Description] IS NULL) THEN N'' ELSE [Extent1].[Description] END LIKE @p__linq__2 ESCAPE N'~')) OR ( EXISTS (SELECT 
            1 AS [C1]
            FROM [dbo].[Files] AS [Extent2]
            WHERE ([Extent1].[TaskId] = [Extent2].[TaskId]) AND ([Extent2].[Name] LIKE @p__linq__3 ESCAPE N'~')
        )) OR ( EXISTS (SELECT 
            1 AS [C1]
            FROM [dbo].[Task_activity] AS [Extent3]
            WHERE ([Extent1].[TaskId] = [Extent3].[TaskId]) AND (2 = [Extent3].[Type]) AND ([Extent3].[Text] LIKE @p__linq__4 ESCAPE N'~')
        )))
    )  AS [GroupBy1]
```

**Comment by icnocop** [comment] 2017-09-24 00:47
This may be duplicate of issue #5

**Closed as completed** 2017-10-17 10:09 UTC
Labels: duplicate
